openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
paths:
  /likes:
    post:
      summary: Like a tweet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                author:
                  type: string
                tweetId:
                  type: string                  
      responses: 
        '201':
          description: Created
        '404':
          description: Not Found
  /likes/{likeId}:
    post:
      summary: Dislike a tweet
      parameters:
        - name: likeId
          in: path
          required: true
          description: Like id
          schema:
            type : string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                author:
                  type: string
      responses: 
        '201':
          description: Created
        '404':
          description: Not Found
  /tweets/{tweetId}/likes:          
    delete:
      summary: Delete all tweets' like
      parameters:
        - name: tweetId
          in: path
          required: true
          description: Tweet id
          schema:
            type : string
      responses: 
        '200':
          description: OK
        '404':
          description: Not Found           